"""Fail safely when publication metadata or likely secrets enter tracked files."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SELF = Path(__file__).relative_to(ROOT).as_posix()

FORBIDDEN_PATHS = (
    re.compile(r"(^|/)\.env($|\.)", re.IGNORECASE),
    re.compile(r"\.(?:pem|p12|pfx|key)$", re.IGNORECASE),
)

CONTENT_RULES = {
    "private key": re.compile(r"BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY"),
    "provider-style secret": re.compile(r"\bsk-[A-Za-z0-9_-]{16,}\b"),
    "GitHub token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
    "AWS access key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "assigned secret": re.compile(r"(?i)\b(?:api[_-]?key|client[_-]?secret|password|passwd)\b\s*[:=]\s*['\"][^'\"]{8,}['\"]"),
    "automated provenance": re.compile(r"(?i)\bgenerated by (?:an? )?(?:ai|llm|automated assistant)\b"),
}


def tracked_files() -> list[str]:
    output = subprocess.check_output(
        ["git", "-c", f"safe.directory={ROOT.as_posix()}", "ls-files", "-z"], cwd=ROOT
    )
    return [item.decode("utf-8") for item in output.split(b"\0") if item]


def main() -> int:
    findings: list[tuple[str, str]] = []
    for relative in tracked_files():
        normalized = relative.replace("\\", "/")
        if normalized == SELF:
            continue
        for rule in FORBIDDEN_PATHS:
            if rule.search(normalized):
                findings.append((normalized, "forbidden publication path"))

        path = ROOT / relative
        try:
            content = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for label, rule in CONTENT_RULES.items():
            if rule.search(content):
                findings.append((normalized, label))

    if findings:
        print("Security scan failed; values are intentionally not printed:")
        for path, label in sorted(set(findings)):
            print(f"- {path}: {label}")
        return 1

    print(f"OK: {len(tracked_files())} tracked files checked for publication leaks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
